import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';

function Learning() {
  const [modules, setModules] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios.get('/api/learning/modules')
      .then(res => {
        setModules(res.data.sort((a, b) => a.order - b.order));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  if (loading) {
    return <div className="loading"><div className="loading-spinner"></div><p>Loading modules...</p></div>;
  }

  return (
    <div className="learning-page">
      <h1>📚 Learning Module</h1>
      <p>Understand every signal generated by the engine. Each module explains one concept used in signal generation.</p>

      <div className="module-grid">
        {modules.map(mod => (
          <Link to={`/learning/${mod.id}`} className="module-card" key={mod.id}>
            <h3>{mod.title}</h3>
            <p>{mod.description}</p>
            <span className={`module-difficulty ${mod.difficulty === 'All Levels' ? 'All' : mod.difficulty}`}>
              {mod.difficulty}
            </span>
          </Link>
        ))}
      </div>
    </div>
  );
}

export default Learning;
