import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { BookOpen, ArrowRight } from 'lucide-react';
import axios from 'axios';

function Learning() {
  const [modules, setModules] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    axios.get('/api/learning/modules')
      .then(res => {
        setModules(res.data.sort((a, b) => a.order - b.order));
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="page-loader">
        <div className="loader-ring"><div className="loader-ring-inner"></div></div>
        <p>Loading modules...</p>
      </div>
    );
  }

  return (
    <div className="learning-page">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1>Learning Module</h1>
        <p>
          Understand every signal generated by the engine. Each module explains one concept used in our 7-rule scoring system.
        </p>
      </motion.div>

      <div className="module-grid">
        {modules.map((mod, idx) => (
          <motion.div
            key={mod.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.05 }}
          >
            <Link to={`/learning/${mod.id}`} className="module-card">
              <h3>{mod.title}</h3>
              <p>{mod.description}</p>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <span className={`module-difficulty ${mod.difficulty === 'All Levels' ? 'All' : mod.difficulty}`}>
                  {mod.difficulty}
                </span>
                <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
              </div>
            </Link>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

export default Learning;
